# -*- coding: utf-8 -*-
"""Movie Recommendation System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmCvibzO0ACgjTWqUpolmiuWt8KWKC_g

**Import Libraries**
"""

import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt

"""**Upload Dataset**"""

from google.colab import files
uploaded = files.upload()

"""**Load Ratings Dataset**"""

ratings = pd.read_csv(
    "u.data",
    sep="\t",
    names=["userId", "movieId", "rating", "timestamp"]
)

ratings.head()

"""**Load Movies Dataset**"""

movies = pd.read_csv(
    "u.item",
    sep="|",
    encoding="latin-1",
    header=None,
    usecols=[0,1],
    names=["movieId", "title"]
)

movies.head()

"""**Explore Dataset**"""

print("Ratings Shape:", ratings.shape)
print("Movies Shape:", movies.shape)

print("Total Users:", ratings['userId'].nunique())
print("Total Movies:", ratings['movieId'].nunique())

"""**Create User-Item Matrix**"""

user_item_matrix = ratings.pivot_table(
    index="userId",
    columns="movieId",
    values="rating"
)

user_item_matrix.head()

"""**Fill Missing Values**"""

user_item_matrix = user_item_matrix.fillna(0)

"""**Compute User Similarity**"""

user_similarity = cosine_similarity(user_item_matrix)

"""**Convert it to dataframe for easier use.**"""

user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_item_matrix.index,
    columns=user_item_matrix.index
)

user_similarity_df.head()

"""**Convert Movie IDs to Movie Titles**"""

def recommend_movies(user_id, num_recommendations=5):

    # Find similar users
    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:6]

    similar_users_ids = similar_users.index

    # Movies watched by similar users
    similar_users_movies = user_item_matrix.loc[similar_users_ids]

    # Average ratings of those movies
    movie_scores = similar_users_movies.mean(axis=0)

    # Movies already watched by the target user
    watched_movies = user_item_matrix.loc[user_id]

    # Filter unseen movies
    movie_scores = movie_scores[watched_movies == 0]

    # Top recommended movies
    recommended_movies = movie_scores.sort_values(ascending=False).head(num_recommendations)

    return recommended_movies

"""**Test the Recommendation System**"""

def get_movie_titles(movie_ids):

    return movies[movies["movieId"].isin(movie_ids)]["title"]

"""**Test the Recommendation System**"""

recommended = recommend_movies(10)

get_movie_titles(recommended.index)

"""**Precision@K Evaluation**"""

def precision_at_k(user_id, recommended_movies, k=5):

    relevant_movies = ratings[
        (ratings["userId"] == user_id) &
        (ratings["rating"] >= 4)
    ]["movieId"]

    recommended_k = recommended_movies[:k]

    relevant_set = set(relevant_movies)
    recommended_set = set(recommended_k)

    precision = len(recommended_set & relevant_set) / k

    return precision

"""**Calculate Precision@5**"""

recommended = recommend_movies(10)

precision = precision_at_k(10, recommended.index, k=5)

print("Precision@5:", precision)

"""**Visualization**"""

recommended = recommend_movies(10)

recommended.plot(kind="bar")

plt.title("Top Recommended Movies Scores")
plt.xlabel("Movie ID")
plt.ylabel("Score")
plt.show()